AllCops:
  TargetRubyVersion: 3.2.1
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/**/*'
    - 'spec/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'Rakefile'
    - 'Capfile'

require:
  - rubocop-rails

Documentation:
  Enabled: false
  
Style/FrozenStringLiteralComment:
  Enabled: false